### PR TITLE
add CHANGELOG

### PR DESCRIPTION
**Pull request by wuputah**
add a CHANGELOG

### CODE REVIEW

**Review by JerrySievert — APPROVED** [review]
lgtm, we should definitely formalize and tag our releases, though, even if there is some slight history modification.

**Review by owenthereal — APPROVED** [review]
Are you planning to use GitHub Releases and add changelog content for corresponding release?

**Comment by wuputah** [comment]
> lgtm, we should definitely formalize and tag our releases, though, even if there is some slight history modification.

I don't plan on inserting "release commits" retroactively but we can add tags to specific commits. In the future we will have a commit that is specifically the release (i.e. usually this is bumping a version number in a file and/or updating the changelog).

> Are you planning to use GitHub Releases and add changelog content for corresponding release?

Roughly the same, not retroactively but we will do this going forward.

**Comment by wuputah** [comment]
proposed tags:
* 6fc0ef0 : `0.1.0-alpha`
* 460893f : `0.2.0-alpha`
* 4f5b508 : `0.3.0-alpha`

**Comment by epompeii** [comment]
I'm not sure if this will fit into your envisioned future workflow, but I've found https://github.com/softprops/action-gh-release very useful for handling releases via GitHub Actions.

The only thing that it doesn't handle well is self-publishing a GitHub Action. That seems to be a non-issue for Hydra though.

**Pull request merged**
