### PR TITLE
[feature] support pg15

### LINKED ISSUE #53: support pg15
* Update columnar code to support pg15
* Everything else has to work with pg15 too

### PR DESCRIPTION
**Pull request by JerrySievert**
This updates columnar and the build system to support postgresql 15.

### What's changed?

* updated columnar code to support the changes from postgres 15
* added a mechanism to build the tests that are built by `pg_regress` in versions older than postgres 15 (https://www.postgresql.org/message-id/1655733.1639871614@sss.pgh.pa.us)
* added alternate test results for postgres 15 output changes
* updated spilo build for 15
* updated the hash for parquet fdw

closes #53 and #59

### CODE REVIEW

**Comment by wuputah** [comment]
note that the upgrade test failure is expected due to `hydra:15` not existing previously. once other reviews are done, I can merge (override the protection).

**Review by owenthereal — COMMENTED** [review]
> note that the upgrade test failure is expected due to hydra:15 not existing previously.

We could manually publish the hydra:15 image in this branch to ghcr.io as the baseline, and the upgrade acceptance test would test the upgrade to the same version, which should always pass. 

We would need to set the max version to 15 for the columnar extension in splio: https://github.com/hydradatabase/hydra/blob/6784a2463294efd66d70c49bf438bcb533c03ec1/files/spilo/postgres-appliance/scripts/spilo_commons.py#L15. I think `pg_ivm` need to be whitelisted [here](https://github.com/hydradatabase/hydra/blob/6784a2463294efd66d70c49bf438bcb533c03ec1/files/spilo/postgres-appliance/scripts/configure_spilo.py#L311-L312) as well.

Besides, Spilo has [a new release](https://github.com/zalando/spilo/releases/tag/3.0-p1). Does it worth upgrading to it?

Deferring the columnar 15 upgrade part to @mkaruza

**Comment by JerrySievert** [comment]
> I think pg_ivm need to be whitelisted [here](https://github.com/hydradatabase/hydra/blob/6784a2463294efd66d70c49bf438bcb533c03ec1/files/spilo/postgres-appliance/scripts/configure_spilo.py#L311-L312) as well.

if we have agreement, I can make that change as part of this PR, but can also make the case that it might be worth a second PR.

> Besides, Spilo has [a new release](https://github.com/zalando/spilo/releases/tag/3.0-p1). Does it worth upgrading to it?

maybe that should be part of a second PR if we decide to do it.

**Review by mkaruza — APPROVED** [review]
lgtm

**Comment by wuputah** [comment]
> We could manually publish the hydra:15 image in this branch to ghcr.io as the baseline, and the upgrade acceptance test would test the upgrade to the same version, which should always pass.

This needs to be done or the image will never get built, because it doesn't build unless the test pass.

**Pull request merged**
