### PR TITLE
[columnar] fix storage id for alter set type

### PR DESCRIPTION
**Pull request by JerrySievert**
fixes tests that inadvertently got broken during a merge.

### CODE REVIEW

**Comment by wuputah** [comment]
we have only the finest storage IDs

**Comment by JerrySievert** [comment]
> we have only the finest storage IDs

like a fine wine, or cheese.  but, all three go bad eventually.

**Comment by wuputah** [comment]
but our 2024 vintage of storage IDs will be our best yet!

**Review by wuputah — APPROVED** [review]
👨‍🍳 😋

**Pull request merged**
