### PR TITLE
[columnar] Raise the maximums for row counts

### PR DESCRIPTION
**Pull request by JerrySievert**
implements #185.

### What's changed?

`columnar.chunk_group_row_limit` and `stripe_row_limit ` maximums set to 10000000.

### CODE REVIEW

**Comment by wuputah** [comment]
is enforcing `chunk_group_row_limit  >= stripe_row_limit` already implemented? just want to make sure we aren't opening up potential weird behavior.

**Comment by JerrySievert** [comment]
>  just want to make sure we aren't opening up potential weird behavior.

we can always try and see what weird behavior it ends up allowing.  we had the ability to mismatch these before this PR.

**Comment by wuputah** [comment]
Yes, for sure; can you please test it?

>  we had the ability to mismatch these before this PR.

That's true, but I'd rather not replace a smaller foot-gun with a larger foot-gun, though both foot-guns would likely have the same result.

**Comment by JerrySievert** [comment]
```
clickbench=# set columnar.chunk_group_row_limit = 1000000;
SET
clickbench=# set columnar.stripe_row_limit = 1000;
SET
clickbench=# create table hits using columnar as select * from hits_orig limit 5000000;
SELECT 5000000
clickbench=# \timing on
Timing is on.
clickbench=# select count(*) from hits;
  count
---------
 5000000
(1 row)

Time: 25.338 ms
```

alternately, with defaults:

```
clickbench=# create table hits using columnar as select * from hits_orig limit 5000000;
SELECT 5000000
clickbench=# \timing on
Timing is on.
clickbench=# select count(*) from hits;
  count
---------
 5000000
(1 row)

Time: 26.616 ms
```

**Comment by wuputah** [comment]
thanks, so I guess it clamps the values itself?

**Review by wuputah — APPROVED** [review]

**Pull request merged**
