### PR TITLE
Remove the deprecated gettext_noop() function

### PR DESCRIPTION
**Pull request by japinli**

### CODE REVIEW

**Comment by JerrySievert** [comment]
I am confused as to what you are trying to accomplish here?

`gettext_noop` is literally a non-operation as it name implies:

```
#define gettext_noop(x) (x)
```

**Comment by japinli** [comment]
> I am confused as to what you are trying to accomplish here?
> 
> `gettext_noop` is literally a non-operation as it name implies:
> 
> ```
> #define gettext_noop(x) (x)
> ```

Yeah, it is non-operation. Throughout the code, `gettext_noop` is used, except for `columnar.planner_debug_level`. This inconsistency is confusing.

**Comment by JerrySievert** [comment]
yes, it is deprecated and needs to be removed, but it has not been a priority for us at this point.

**Comment by JerrySievert** [comment]
if you'd like to create a PR removing the instances, that would be awesome, but I'd be hesitant to add any more :)

**Review by mkaruza — APPROVED** [review]

**Pull request merged**
