### PR TITLE
Disable cache-to/cache-from local disk in CI

### PR DESCRIPTION
**Pull request by jacobwgillespie**
This is a fix for intermittent `(*service).Write failed` image build errors in CI.

cc @wuputah

Currently the `docker-bake.hcl` file has a `cache-to` and `cache-from` local disk like the following:

```hcl
cache-to = ["type=local,dest=tmp/bake_cache/TARGET"]
cache-from = ["type=local,src=tmp/bake_cache/TARGET"]
```

This means that as each bake target builds, it downloads a copy of the layer cache to the local disk. Each bake target builds in parallel, and cache is exported as soon as it's available. Additionally, when one bake target depends on another, for instance `postgres` embedding `s3`, the `cache-to` destination of each target gets a copy of `s3`'s layers.

This means that it's possible for two targets to try to export the same cache layer at the same time. The first export acquires a lock while it downloads the layer, and the second export waits for that lock, but sometimes it's not fast enough to download that layer before the second lock times out. That throws an error, which is what you've seen in CI.

### What's changed?

This PR uses `set` to disable the `cache-to` and `cache-from` in CI. Since the GitHub Actions runner is ephemeral, there's no reason to download a duplicate copy of the cache data during the build. The cache for a build of the `postgres` target is about 1GB in size, so in addition to making things more stable, this PR should speed up the build itself, as it can skip downloading all that data.

I'm not entirely sure if you need `cache-to` / `cache-from` for your local builds either, since the cache data would already be stored in Docker's internal cache anyways. If that's the case, I'm happy to update this PR to remove them from the `docker-bake.hcl` entirely.

### CODE REVIEW

**Comment by owenthereal** [comment]
@jacobwgillespie:

Thanks for the contribution!

> I'm not entirely sure if you need cache-to / cache-from for your local builds either, since the cache data would already be stored in Docker's internal cache anyways.

Yup, we could remove the `cache-to` & `cache-from` from the bake file. If we want to rebuild cache we could always add the `--no-cache` flag. These two fields are set IIRC is to move the cache location to `tmp/bake_cache/*` in the project for easier investigation. But none of us really looked into the cache since then so we are good to remove it IMO.

**Comment by jacobwgillespie** [comment]
@owenthereal awesome, I've updated the PR to remove `cache-to` and `cache-from` from the bakefile 👍

**Comment by owenthereal** [comment]
Thanks @jacobwgillespie! Mind answering [this question](https://github.com/hydradatabase/hydra/pull/114/files/2e98cf5322ef13326abd6a803f4ac9e65d650d67#diff-8f993d97f1b381fe65fb7677db3bf5f0d03a32899c8e904c3cfe421a33805058)? Would it be possible that we enable `gha` when using depot?

**Comment by jacobwgillespie** [comment]
Hey, I think GitHub lost the question (I'm not seeing anything at that link).

It is technically possible to cache-to and from `gha` with Depot, but we don't recommend it, from our experience the GitHub Actions Cache API has frequent downtime and network issues across the builds we've observed. It's also potentially redundant when using Depot, since Depot projects have persistent cache already. But I may be missing what you're trying to accomplish

**Comment by owenthereal** [comment]
> It's also potentially redundant when using Depot, since Depot projects have persistent cache already. 

👍

**Review by owenthereal — APPROVED** [review]

**Pull request merged**
