### PR TITLE
[columnar] Fix corruption possibilities for vacuum UDF

### LINKED ISSUE #169: [Bug]: Stopping columnar vacuum can result in table corruption
### What's wrong?

I was testing Updating a row and than running the columnar.vacuum_full().
Because it was taking to long I stopped that one and run a more precise columnar.vacuum for the specific partitioned table.
Something happened and I got the error:
`ERROR:  attempt to read columnar data of length 8168 from offset 24 of block 3927 of relation 29101
CONTEXT:  SQL statement "SELECT columnar.vacuum(tablename, stripe_count)"
PL/pgSQL function columnar.vacuum_full(name,real,integer) line 25 at SQL statement`

If I now run a select on that table I get this error:
`ERROR:  Unknown frame descriptorzstd decompression failed 
ERROR:  zstd decompression failed
SQL state: XX000
Detail: Unknown frame descriptor`

### PR DESCRIPTION
**Pull request by JerrySievert**
this should fix #169.

there are two parts to the vacuum UDF:

* combining stripes with deleted data
* moving stripes into the new holes

bailing out in the combination process is not an issue, but bailing out during the reorganization is.  if we exit cleanly from the signal handlers, instead of calling the signal after we feel we are safe, we do not have corruption.  unfortunately, not calling the signal that we blocked is not an acceptable solution.

interestingly, finishing a single reorganization does not corrupt, even if the signal handlers are called.  this PR sets up the vacuum UDF to do a singular reorganization, renames the UDF to `columnar._vacuum_internal`, and creates a new `columnar.vacuum` that recreates the original functionality by continually calling the `columnar._vacuum_internal` either until done, or we reach the optional count.

this does add additional time to the UDF.

note that this does increase the version of columnar, so we will need to upgrade the extension to fully fix the problem.

### CODE REVIEW

**Comment by JerrySievert** [comment]
I've also added `elog` statements at `DEBUG3` which announce state transitions, so it should be fairly easy to test if you set your statement level to `DEBUG3` and cancel/terminate after beginning reorganization.

**Review by mkaruza — APPROVED** [review]
lgtm

**Comment by muntdan** [comment]
> note that this does increase the version of columnar, so we will need to upgrade the extension to fully fix the problem.

This means a new Tag/version will be published for this ?

**Comment by wuputah** [comment]
every commit to main (well, any commit modifies code) has a build and tag. See:
https://github.com/hydradatabase/hydra/pkgs/container/hydra

I do plan on publishing a 1.0.2 release soon, but would be grateful for any testing you could do with the current build.

**Comment by muntdan** [comment]
So the “upgrade the extension" is included in the latest docker build?

**Comment by wuputah** [comment]
This means you need to run `ALTER EXTENSION columnar UPDATE;` with any existing databases after upgrading to the new build.

**Pull request merged**
